### ISSUE TITLE
Top-n gating bug

### ISSUE THREAD

**Issue by lihenglin** [lucidrains/st-moe-pytorch#13]
I'm wondering if https://github.com/lucidrains/st-moe-pytorch/blob/6b7f7fbb93610134c902efdfe096e06fe5a7d6b5/st_moe_pytorch/st_moe_pytorch.py#L489 should be
`prev_expert_count = reduce(mask[n], '... n e -> ... 1 e', 'sum') + prev_expert_count` instead.

The original code will potentially have a bug if n > 2.

**Comment by lucidrains** [comment]
@lihenglin hey Li-Heng! yes you are correct 🤦 thank you
