### ISSUE TITLE
Implementing LIMoE from Google zurich

### ISSUE THREAD

**Issue by prateeky2806** [lucidrains/st-moe-pytorch#2]
Hi, I was going over the readme, and seems like you are looking for suggestions on other MoE models. I was wondering if you would want to implement [LIMoE](https://arxiv.org/pdf/2206.02770.pdf) which is a multimodal MoE model. Let me know what you think. 

Thanks,
Prateek

**Comment by lucidrains** [comment]
@prateeky2806 i don't think this work really has anything new. they simply shared one MoE for all modalities for contrastive learning

you can use https://github.com/lucidrains/soft-moe-pytorch which works for an encoder setup
